kind: pipeline
type: docker
name: test

steps:
  - name: Test Python
    image: python:3.12
    commands:
      - curl -L "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-$(dpkg --print-architecture)" > "${HOME}/bin/cc-test-reporter"
      - chmod +x "${HOME}/bin/cc-test-reporter"
      - pip install -r requirements-test.txt
      - ruff check .
      - mypy . --strict --exclude build
      - python setup.py develop
      - cc-test-reporter before-build
      - coverage run -m unittest
      - exitcode="$?"
      - coverage report -m
      - coverage xml
      - cc-test-reporter after-build --exit-code "$exitcode"
    environment:
      CC_TEST_REPORTER_ID: 3aedff2168eb5cbde21c068607a0b3938e6174ecadb9928d7318661ace2eb1a4

  - name: Test Python Packaging
    image: python:3.12-slim
    commands:
      - pip install twine
      - python setup.py sdist bdist_wheel
      - twine check --strict dist/*

  - name: Upload Python
    depends_on:
      - Test Python
      - Test Python Packaging
    environment:
      TWINE_USERNAME:
        from_secret: twine_username
      TWINE_PASSWORD:
        from_secret: twine_password
    image: python:3.12-slim
    commands:
      - pip install twine
      - python setup.py sdist bdist_wheel
      - twine upload dist/*
    when:
      event:
        - tag
